### ISSUE TITLE
Plugin fails to load on Hopper 4.7.0

### ISSUE THREAD

**Issue by philpem** [agatti/hopper-plugins#4]
I'm trying to use the 6502 plugin with Hopper 4.7.0. I've successfully built the plugin with Xcode, and it's been copied to the correct location. When I open Hopper and import a binary file, Hopper's internal MOS 6502 CPU support is available from the CPU dropdown but not the built plugin.

I see the same behaviour with the 8x300 plugin.

The plugin does not appear in the Hopper Preferences (Plugins tab) either.

I've also tried building the plugin for Linux, and had the same result. Hopper can't see the plugin.

Can the 6502 plugin be updated to support Hopper 4.7?

**Comment by philpem** [comment]
Further debugging:

I replaced the Hopper SDK include files in my clone with those from the Hopper 4.7.0 SDK. This resulted in an "Unsupported SDK version" error from HopperCommon.h. Commenting out this line, cleaning and rebuilding seems to be enough to get Hopper to detect the plugin. It seems to work too, but probably needs more testing.

**Comment by agatti** [comment]
Looks like you already found a viable solution.  I seem to recall that Hopper would still be able to use plugins built against an earlier SDK version but, unless I was misremembering all along, this seems to not be the case anymore.

However, I'll update the SDK headers and upgrade the plugins ASAP - thank you for letting me know.

**Comment by agatti** [comment]
https://github.com/agatti/hopper-plugins/commit/2cd80924967d95d3aea346e68796f48efe548f6a should fix things up - feel free to give it a try and reopen this if anything's wrong (it seems to work OK on my end).
